name:                backend
version:             0.1.0.0
github:              "folq/haskell-to-elm-test/backend"
license:             BSD3
author:              "Olle Fredriksson"
maintainer:          "fredriksson.olle@gmail.com"
copyright:           "2019 Olle Fredriksson"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/folq/haskell-to-elm-test/backend#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

dependencies:
- aeson
- base >= 4.7 && < 5
- directory
- elm-syntax
- filepath
- haskell-to-elm
- protolude
- servant
- servant-elm
- servant-elm-bidirectional
- servant-foreign-bidirectional
- servant-server
- text
- unordered-containers
- wai-cors
- wai-extra
- warp

library:
  source-dirs: src

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:         *exe-ghc-options
    dependencies:
    - backend

  elm-generator:
    main:                Main.hs
    source-dirs:         elm-generator
    ghc-options:         *exe-ghc-options
    dependencies:
    - backend

tests:
  backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
